import { TaxFields } from 'src/app/shared/_models/tax.model';

export let non_tax_codes: TaxFields[] = [
  {
    Code: 'T13',
    Desc_en: 'Stamping tax (percentage)',
    Desc_ar: 'ضريبه الدمغه (نسبيه)',
    rate: true,
    amount: false,
    sub_tax: [],
    taxable: false,
  },
  {
    Code: 'T14',
    Desc_en: 'Stamping Tax (amount)',
    Desc_ar: 'ضريبه الدمغه (قطعيه بمقدار ثابت )',
    rate: true,
    amount: false,
    sub_tax: [],
    taxable: false,
  },
  {
    Code: 'T15',
    Desc_en: 'Entertainment tax',
    Desc_ar: 'ضريبة الملاهى',
    rate: true,
    amount: false,
    sub_tax: [],
    taxable: false,
  },
  {
    Code: 'T16',
    Desc_en: 'Resource development fee',
    Desc_ar: 'رسم تنميه الموارد',
    rate: true,
    amount: false,
    sub_tax: [],
    taxable: false,
  },
  {
    Code: 'T17',
    Desc_en: 'Table tax (percentage)',
    Desc_ar: 'رسم خدمة',
    rate: true,
    amount: false,
    sub_tax: [],
    taxable: false,
  },
  {
    Code: 'T18',
    Desc_en: 'Municipality Fees',
    Desc_ar: 'رسم المحليات',
    rate: true,
    amount: false,
    sub_tax: [],
    taxable: false,
  },
  {
    Code: 'T19',
    Desc_en: 'Medical insurance fee',
    Desc_ar: 'رسم التامين الصحى',
    rate: true,
    amount: false,
    sub_tax: [],
    taxable: false,
  },
  {
    Code: 'T20',
    Desc_en: 'Other fees',
    Desc_ar: 'رسوم أخرى',
    rate: true,
    amount: false,
    sub_tax: [],
    taxable: false,
  },
];
